server:
  port: 8081
spring:
  application:
    name: personal-center
mysql:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/personal?useUnicode=true&charactorEncoding=utf8
    userName: root
    password: 123456