server:
  port: 8088

#配置mysql数据源
mysql:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/farm?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
#打印sql语句
#logging:
#  level:
#    com:
#      jiemin:
#        wages:
#          mapper: DEBUG
#thymelea模板配置
spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    servlet:
      content-type: text/html
    cache: false
  resources:
    chain:
      strategy:
        content:
          enabled: true
          paths: /**
